[build]
  command = "hugo $https://www.chantaldamore.com/"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo $DEPLOY_PRIME_URL"
